In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('Integrated Version.csv')

In [3]:
df.head()

Unnamed: 0      block  month  index  bathrooms  bedrooms  \
0           0   Brooklyn      6      4        1.0         1   
1           1  Manhattan      6      6        1.0         2   
2           2  Manhattan      6      9        1.0         2   
3           3   Brooklyn      6     10        1.5         3   
4           4  Manhattan      6     15        1.0         0   

                        building_id              created  \
0  8579a0b0d54db803821a35a4a615e97a  2016-06-16 05:55:27   
1  b8e75fc949a6cd8225b455648a951712  2016-06-01 05:44:33   
2  cd759a988b8f23924b5a2058d5ab2b49  2016-06-14 15:19:59   
3  53a5b119ba8f7b61d4e010512e0dfc85  2016-06-24 07:54:24   
4  bfb9405149bfff42a92980b594c28234  2016-06-28 03:50:23   

                                         description      display_address  \
0  Spacious 1 Bedroom 1 Bathroom in Williamsburg!...  145 Borinquen Place   
1  BRAND NEW GUT RENOVATED TRUE 2 BEDROOMFind you...            East 44th   
2  **FLEX 2 BEDROOM WITH FULL PRESSURIZED WALL**L...     East 56th Street   
3  A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...  Metropolitan Avenue   
4  Over-sized Studio w abundant closets. Availabl...     East 34th Street   

   ... windowed kitchen  wine cooler.   Subway  \
0  ...              0.0           0.0      0.0   
1  ...              0.0           0.0      0.0   
2  ...              0.0           0.0      0.0   
3  ...              0.0           0.0      0.0   
4  ...              0.0           0.0      0.0   

   • On-site lifestyle concierge by Luxury Attaché •24/7 Doorman • State of the art cardiovascular and weight training equipment • 24-hour valet parking garage • Valet services including dry cleaning  \
0                                                0.0                                                                                                                                                      
1                                                0.0                                                                                                                                                      
2                                                0.0                                                                                                                                                      
3                                                0.0                                                                                                                                                      
4                                                0.0                                                                                                                                                      

  label Brooklyn  Manhattan Queens The Bronx  Staten Island  
0     1        1          0      0         0              0  
1     0        0          1      0         0              0  
2     1        0          1      0         0              0  
3     1        1          0      0         0              0  
4     0        0          1      0         0              0  

[5 rows x 1584 columns]

In [4]:
import re
regex = re.compile(r"\[|\]|<", re.IGNORECASE)

df.columns = [regex.sub("_", col) if any(x in str(col) for x in set(('[', ']', '<'))) else col for col in df.columns.values]

In [5]:
col = df.columns.values.tolist()
col.remove('label')
col.remove('block')
col.remove('index')
col.remove('building_id')
col.remove('created')
col.remove('description')
col.remove('display_address')
col.remove('manager_id')
col.remove('photos')
col.remove('street_address')
col.remove('interest_level')
col.remove('features')
col.remove('Unnamed: 0')
col.remove('listing_id')
X = df[col].copy()
X

month  bathrooms  bedrooms  latitude  longitude  price  street_code  \
0          6        1.0         1   40.7108   -73.9539   2400            5   
1          6        1.0         2   40.7513   -73.9722   3800            7   
2          6        1.0         2   40.7575   -73.9625   3495           39   
3          6        1.5         3   40.7145   -73.9425   3000            3   
4          6        1.0         0   40.7439   -73.9743   2795           38   
...      ...        ...       ...       ...        ...    ...          ...   
49222      4        1.0         0   40.7640   -73.9917   2175            2   
49223      4        1.0         3   40.8433   -73.9396   2800            5   
49224      4        1.0         2   40.8198   -73.9578   2395          174   
49225      4        1.0         1   40.5765   -73.9554   1850            2   
49226      4        1.0         2   40.7448   -74.0017   4195            6   

       building_code  manager_code  !!!!LOW FEE!!!!  ...  well-maintained  \
0                  5           112              0.0  ...              0.0   
1                 51            26              0.0  ...              0.0   
2                 71            93              0.0  ...              0.0   
3                  3            90              0.0  ...              0.0   
4                 86            55              0.0  ...              0.0   
...              ...           ...              ...  ...              ...   
49222           8286           222              0.0  ...              0.0   
49223              5            10              0.0  ...              0.0   
49224            126            14              0.0  ...              0.0   
49225              6           112              0.0  ...              0.0   
49226             12            33              0.0  ...              0.0   

       windowed kitchen  wine cooler.   Subway  \
0                   0.0           0.0      0.0   
1                   0.0           0.0      0.0   
2                   0.0           0.0      0.0   
3                   0.0           0.0      0.0   
4                   0.0           0.0      0.0   
...                 ...           ...      ...   
49222               0.0           0.0      0.0   
49223               0.0           0.0      0.0   
49224               0.0           0.0      0.0   
49225               0.0           0.0      0.0   
49226               0.0           0.0      0.0   

       • On-site lifestyle concierge by Luxury Attaché •24/7 Doorman • State of the art cardiovascular and weight training equipment • 24-hour valet parking garage • Valet services including dry cleaning  \
0                                                    0.0                                                                                                                                                      
1                                                    0.0                                                                                                                                                      
2                                                    0.0                                                                                                                                                      
3                                                    0.0                                                                                                                                                      
4                                                    0.0                                                                                                                                                      
...                                                  ...                                                                                                                                                      
49222                                                0.0                                       

In [6]:
y = df[['label']]
y

label
0          1
1          0
2          1
3          1
4          0
...      ...
49222      0
49223      0
49224      1
49225      1
49226      1

[49227 rows x 1 columns]

In [7]:
y.to_numpy()

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [8]:
y.shape


(49227, 1)

In [9]:
y = y.values.ravel()

In [10]:
y.shape


(49227,)

In [11]:
from sklearn.model_selection import train_test_split

# 将数据集一分为二，训练数据占70%，测试数据占30%
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 1024)


In [12]:
X_train.shape

(34458, 1570)

## 训练算法

In [13]:
from sklearn.ensemble import AdaBoostClassifier

In [30]:
ada = AdaBoostClassifier(n_estimators=3,algorithm='SAMME',learning_rate=10) ##谷哥看这里！！！
ada.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME', base_estimator=None, learning_rate=10,
                   n_estimators=3, random_state=None)

In [31]:
y_predict = ada.predict(X_test)

In [32]:
y_predict

array([2, 2, 2, ..., 2, 2, 2], dtype=int64)

In [33]:
y_predict  = pd.DataFrame(y_predict)

y_predict

0
0      2
1      2
2      2
3      2
4      1
...   ..
14764  2
14765  2
14766  2
14767  2
14768  2

[14769 rows x 1 columns]

In [18]:
y_predict.columns = ['y_predict']
y_predict

y_predict
0              2
1              2
2              2
3              2
4              1
...          ...
14764          2
14765          2
14766          2
14767          2
14768          2

[14769 rows x 1 columns]

In [19]:
y_predict.describe()

y_predict
count  14769.000000
mean       1.948541
std        0.220940
min        1.000000
25%        2.000000
50%        2.000000
75%        2.000000
max        2.000000

## 1）首先计算第一个弱分类器权重，并更新样本权重。

In [20]:
X_train.shape

(34458, 1570)

In [21]:
ada = AdaBoostClassifier(n_estimators=3,algorithm='SAMME',learning_rate=3.0)
ada.fit(X_train,y_train)


learning_rate = 3.0
num = 3
# 初始化样本权重，每个样本的权重相同
w0 = np.full(shape = 34458,fill_value=1/34458)  #X_train 内部一共有38391个样本
# 计算弱分类器误差
y1 = ada[0].predict(X_train)  
e1 = ((y1 != y_train)*w0).sum()  # y1为弱分类器的预测值，y_train为真实值
# 计算弱分类器权重
a1 = np.round(learning_rate*(np.log((1-e1)/e1) + np.log(num - 1)),8)
# 更新样本权重
w1 = w0*np.exp(a1*(y_train != y1))
w1 /= w1.sum()


## 2）计算第二个弱分类器权重，更新样本权重

In [22]:
# 计算弱分类器误差
y2 = ada[1].predict(X_train)
e2 = ((y2 != y_train)*w1).sum()
# 计算弱分类器权重
a2 = np.round(learning_rate*(np.log((1-e2)/e2) + np.log(num - 1)),8)
# 更新样本权重
w2 = w1*np.exp(a2*(y_train != y2))
w2 /= w2.sum()


## 3）计算第三个弱分类器权重，更新样本权重

In [23]:
# 计算弱分类器误差
y3 = ada[2].predict(X_train)#y1弱学习器预测值，y_train真实
e3 = ((y3 != y_train)*w2).sum()
# 计算弱分类器权重
a3 = np.round(learning_rate*(np.log((1-e3)/e3) + np.log(num - 1)),8)
# 更新样本权重
w3 = w2*np.exp(a3*(y_train != y3))
w3 /= w3.sum()


## 4）由3个弱分类器组合成强分类器。

In [24]:
# 第一个弱分类器的预测结果
y1_ = (ada[0].predict(X_test) == np.array([[0],[1],[2]])).T.astype(np.int8)
# 第二个弱分类器的预测结果
y2_ = (ada[1].predict(X_test) == np.array([[0],[1],[2]])).T.astype(np.int8)
# 第三个弱分类器的预测结果
y3_ = (ada[2].predict(X_test) == np.array([[0],[1],[2]])).T.astype(np.int8)
F = y1_*a1 + y2_*a2 + y3_*a3


## 5）分类预测

In [25]:
estimator_weights = np.array([a1, a2, a3])
F /= estimator_weights.sum()
F /= (num -1)
# softmax处理，将结果转化为概率，使得大的值变的更大，小的值变得更小
pred = np.e**F/((np.e**F).sum(axis = 1).reshape(-1,1))
pred = np.argmax(pred, axis=1)
# 预测结果
pred


array([2, 2, 2, ..., 2, 2, 2], dtype=int64)